SIMOD_LOG_READER_CASE_ID_COLUMN_NAME = 'caseid'
SIMOD_LOG_READER_ACTIVITY_COLUMN_NAME = 'task'
SIMOD_START_TIMESTAMP_COLUMN_NAME = 'start_timestamp'
SIMOD_END_TIMESTAMP_COLUMN_NAME = 'end_timestamp'
SIMOD_RESOURCE_COLUMN_NAME = 'user'

PM4PY_ACTIVITY_COLUMN_NAME = 'concept:name'
PM4PY_CASE_ID_COLUMN_NAME = 'case:concept:name'
PM4PY_START_TIMESTAMP_COLUMN_NAME = 'start_timestamp'
PM4PY_END_TIMESTAMP_COLUMN_NAME = "time:timestamp"

DURATION_COLUMN_NAME = "@@duration"

EMPTY_NON_NUMERICAL_VALUE = "<NONE>"
