# Based on: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  RUNNING_TESTS: 1

jobs:
  build-test-ubuntu:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Create & activate venv
        run: |
          python3 -m venv env
          source env/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest wheel
          pip install -r requirements.txt

      - name: Install graphviz backend
        run: sudo apt install graphviz

      - name: Pre-flight check (test only pipeline)
        run: |
          cd knockout_ios
          pytest -m "pipeline" --disable-warnings

      - name: Run full test suite (pytest parallel)
        run: |
          cd knockout_ios
          pytest . -x -n auto --disable-warnings

  build-test-windows:

    runs-on: windows-latest
    needs: build-test-ubuntu
    
    steps:

      - uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Create & activate venv
        run: |
          py -m venv env
          .\env\Scripts\activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest wheel
          pip install -r requirements.txt

      - name: Install graphviz backend
        run: choco install graphviz

      - name: Pre-flight check (test only pipeline)
        run: |
          cd knockout_ios
          pytest -m "pipeline" --disable-warnings

      - name: Run full test suite (pytest parallel)
        run: |
          cd knockout_ios
          pytest . -x -n auto --disable-warnings
